name: Deploy to DEV.
on:
  push:
    branches: [github-actions]

jobs:
  build:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
    - name: cd to dir
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
        script: cd ${{ secrets.PLUGINS_HQ_DEV_PATH }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: github-actions

    - name: Build and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLUGINS_HQ_HOST }}
        username: ${{ secrets.PLUGINS_HQ_USERNAME }}
        key: ${{ secrets.PLUGINS_HQ_SECRET_KEY }}
        port: ${{ secrets.PLUGINS_HQ_PORT }}
        script: |
          cd docker
          ./build.sh
          ./deploy.sh
